baseurl: https://shanescaggs.netlify.app/
languageCode: en-us
title: Shane A. Scaggs
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
  Data Science: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Data Science
      url: /Data Science/
      weight: 3
    - name: Simulations
      url: /sims/
      weight: 4
    - name: CV
      url: /cv/
      weight: 2
    #- name: Data Art
    #  url: /data_art/
    #  weight: 5
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: The personal website of Shane A. Scaggs.
  favicon: 'images/pix_mustache2_haw.png'
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 60
    url: pix_mustache2_header.png
    width: 60
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
      codeFences: true
      noClasses: true
      style: Nord 

