---
title: Writing grants for the NSF
author: Shane A. Scaggs
date: '2021-12-20'
slug: writing-grants-for-the-nsf
categories:
  - Research
tags:
  - grant writing
  - writing
  - research funding
output:
    blogdown::html_page:
        toc: true
bibliography: grants.bib
draft: yes
---


# Motivation

As a young scholar, I have had decent success writing and submitting grants to the National Science Foundation (NSF). In the final year of my masters, I received the Graduate Research Fellowship (GRF) from the National Science Foundation, and in the summer of 2021, my proposal to the Cultural Anthropology program of the Doctoral Dissertation Research Improvement Grant (DDRIG) was recommended for funding. I am also part of a research team that just resubmitted to DISES program (Dynamics of Integrated Social Environmental Systems) after receiving a "Competitive - Low" rating last year. 

Each of these grants is different. The GRF funds a *person* with the goal of helping them develop into a scientist The DDRIG, in contrast, funds a *project* that is representative of the goals of the NSF, and the program that receives the proposal. The DISES program funds a inter/transdisciplinary *team* that is collectively trying to move the goal posts in covergence research.  

In this post, I want to summarize some of my thoughts about writing for the NSF and provide details and tips about going through the process. Why? Because I remember when grant funding seemed like a mystical process. Getting funded by the NSF seemed so far beyond me. It was only by readings posts like this one and learning from great mentors that I was successful. 

# The GRFP 

The [Graduate Research Fellowship Program](https://www.nsfgrfp.org/) is a five-year fellowship that provides a cost of education allowance (up to `$12,000`) and a `$34,000` stipend for three of the five years while a student is pursuing their doctorate. A 2021 study showed that GRFP recipients tend to publish more, are cited more often, and are more likely to be placed in post-doctoral or academic research positions after they graduate [@graddy2021training]. 

Students applying to the GRFP need prepare a three-page personal statement, a two-page project proposal, and a Curriculum Vitae to go alongside three recommendation letters and a school transcript. It is important to prepare these documents well in advance so, mainly so that you can receive adequate feedback and give your letter writers enough time to prepare their recommendation. 

## Tip 1: Don't over-write your personal statement

I know I said that you should prepare documents in advance, but this can also lead prospective fellows to over-write their personal statements. Because there are only three pages available, I find that students want to try and cram everything that they can into these pages. This does not help reviewers. Actually, it makes their job harder because cramming everything in makes your documents read more like a jumbled list, and less like a narrative. 

Rather than listing as many experiences as possible, focus on specific experiences. Use the personal statement to describe the passions and skills you wanted to pursue, and how you intentionally got involved in projects so that you could pursue them. 

## Tip 2: Visualize your trajectory as a scientist 

Your personal statement is meant to be a narrative -- it is a story. For some people, myself included, these narratives can be difficult to write. So help yourself out by taking time to reflect on where you've been and to visualize a trajectory for your career as a scientist. 

Treat your narrative just as a fiction writer might treat their novel. What is the story arc? Where and when is the story set? How does the protagonist (you) develop? In a personal statement, you have a distinct advantage over the fiction writer because you don't have to make up all the details from scratch. 

Your job is to show the reviewer how the story has started and help them picture how the story could climax and end, ultimately with you flourishing as a budding scientist. Don't let imposter syndrome sneak in at this point. Instead, spend time building yourself up by imagining the possibilities! Let your enthusiasm for science and your interests set the tone for the narrative.

## Tip 3: Remember your CV 

Think of your CV as the "outline" for your narrative. It is the skeleton for the story about what you've done in the past. Luckily, your reviewers have a copy of your CV. This means you actually don't have to talk about everything. Instead, ask yourself what you reviewers need to know to understand what youve been up to.

For example, maybe you volunteered for a lot of student and community organizations during your undergad. Don't list them all. Just focus on the most significant and use prose to allude to that fact that you've been very volunteer oriented as a student. Let your CV be an exhustive list and use your personal narrative fills in the gaps and provide context.

## Tip 4: Institutional support is important

The GRFP is primarily interested in you as a potential scientist. But this does not mean that you should only talk about yourself. You should also show that you are at an institution (or seeking institutions) where you will have the right kind of institutional support to pursue your research interests. 

In my GRFP, I talked extensively about my interest in problems where social and ecological processes converge. I made a point of mentioning that the university I was attend had entire departments and research institutes that are dedicated to these kinds of interdiscplinary problems. I also made it clear that although I was a anthropology student, I was at an institution where I could take the  appropriate courses in ecology and environmental sciences to sufficiently tackle questions that span the social and ecological domains that I'm interested in.  

## Tip 5: People, not projects

Ultimately, your research proposal is important, not necessarily because you will be tackling an original cutting edge problem, but because you can use it to demonstrate your ability to weave together theory and method. This is your chance to show that you are capable of formulating a research problem, identifying the theories people have used to explain the problem in the past, and choosing appropriate methods to collect data to gain new insights. 

But don't rely on a kick ass idea to get you through. All it takes is one reviewer who thinks your ideas is bogus to kill that portion of the application. Place as much or more focus on the narrative. when drafting your proposal, spend the most time making sure that your research question, theoretical background, and methods are tightly integrated in the proposal. 

## Tip 6: Citations

There is so little space in the proposal and references cited take up some of that space in the proposal. Choose strong high profile citations. Use a citation format that uses numerical in-line citations.

## Parting thoughts 

Above all else, remember that the GRFP is unique because it is an investment in the future generation of scientists. So you should place a lot of focus on developing why you are worthy of this investment. This sounds very economic and even somewhat crass. And that's because it is. Program directors are literally trying to justify why you are money well spent. Do as much of their job for them by creating a compelling story about how you, with the right funding, are destined to become a prolific scientist. 

# The DDRIG 

