---
title: "Curriculum Vitae"
author: "Shane A. Scaggs"
#date: "7/22/2021"
#output: html_document
---

```{r setup, include=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
```


## Title & Affiliation
<p style="text-align: left;">
Graduate Research Fellow<br>
[Human Complexity Lab](https://u.osu.edu/hclab/)<br>
Department of Anthropology<br>
The Ohio State University<br>
scaggs.32@osu.edu</p>



## Education

```{r,echo=F}
edu <- read.csv(file = "~/Shane's Projects/folio/static/csv/edu.csv")
knitr::kable(edu)
```

## Publications

```{r,echo=F}
pubs <- read.csv(file = "~/Shane's Projects/folio/static/csv/pubs.csv")
colnames(pubs) <- c('Year','Citation','DOI','Type')

pubs[,1:3] %>% 
    arrange(desc(Year)) %>%
    kbl()  

```

## Funding Support

```{r,echo=F}
funds <- read.csv(file = "~/Shane's Projects/folio/static/csv/funds.csv")
colnames(funds) <- c("Year","Title","Funding Agency","Amount")
knitr::kable(funds)
```

## Conference Proceedings 

```{r,echo=F}
conf <- read.csv(file = "~/Shane's Projects/folio/static/csv/conf.csv")
colnames(conf) <- c("Year","Title","Meeting","Type")
conf[,1:4] %>% 
    arrange(desc( Year)) %>%
    kbl()  

```
